### ISSUE TITLE
Crash on Windows

### ISSUE THREAD

**Issue by SteveRussell33** [alefnull/alefsbits#5]
Using commit e6c230dfd735f51c09f336cab5893a9866a75bd5
```
Thread 1 received signal SIGSEGV, Segmentation fault.
0x00007ffb37207545 in Scope::drawBackground (this=this@entry=0x89ac7d0, args=...) at src/widgets/Scope.cpp:152
152         withFill(args, data->backgroundColor, [=] {
(gdb) bt
#0  0x00007ffb37207545 in Scope::drawBackground (this=this@entry=0x89ac7d0, args=...) at src/widgets/Scope.cpp:152
#1  0x00007ffb372075f2 in Scope::draw (this=0x89ac7d0, args=...) at src/widgets/Scope.cpp:160
#2  0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x899cdc0, child=0x89ac7d0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#3  0x00007ffb31a54982 in rack::widget::Widget::draw (this=this@entry=0x899cdc0, args=...) at src/widget/Widget.cpp:280
#4  0x00007ffb31a19b1a in rack::app::ModuleWidget::draw (this=0x899cdc0, args=...) at src/app/ModuleWidget.cpp:213
#5  0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x899cc60, child=0x899cdc0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#6  0x00007ffb31a54982 in rack::widget::Widget::draw (this=this@entry=0x899cc60, args=...) at src/widget/Widget.cpp:280
#7  0x00007ffb31a51fe3 in rack::widget::FramebufferWidget::drawFramebuffer (this=0x899cc60) at src/widget/FramebufferWidget.cpp:293
#8  0x00007ffb31a52ad9 in rack::widget::FramebufferWidget::render (this=0x899cc60, scale=..., offsetF=..., clipBox=...) at src/widget/FramebufferWidget.cpp:247
#9  0x00007ffb31a53152 in rack::widget::FramebufferWidget::draw (this=0x899cc60, args=...) at src/widget/FramebufferWidget.cpp:130
#10 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x899cb90, child=0x899cc60, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#11 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x899cb90, args=...) at src/widget/Widget.cpp:280
#12 0x00007ffb31a54c0d in rack::widget::ZoomWidget::draw (this=0x899cb90, args=...) at src/widget/ZoomWidget.cpp:54
#13 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x8160450, child=0x899cb90, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#14 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x8160450, args=...) at src/widget/Widget.cpp:280
#15 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x81603a0, child=0x8160450, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#16 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x81603a0, args=...) at src/widget/Widget.cpp:280
#17 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x684f560, child=0x81603a0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#18 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x684f560, args=...) at src/widget/Widget.cpp:280
#19 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x684f490, child=0x684f560, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#20 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x684f490, args=...) at src/widget/Widget.cpp:280
#21 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x684f1b0, child=0x684f490, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#22 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x684f1b0, args=...) at src/widget/Widget.cpp:280
#23 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x684f0f0, child=0x684f1b0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#24 0x00007ffb31a54982 in rack::widget::Widget::draw (this=this@entry=0x684f0f0, args=...) at src/widget/Widget.cpp:280
#25 0x00007ffb31a4d8ef in rack::ui::ScrollWidget::draw (this=0x684f0f0, args=...) at src/ui/ScrollWidget.cpp:68
#26 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x69249e0, child=0x684f0f0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#27 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x69249e0, args=...) at src/widget/Widget.cpp:280
#28 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x862c9b0, child=0x69249e0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#29 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x862c9b0, args=...) at src/widget/Widget.cpp:280
#30 0x00007ffb31a54868 in rack::widget::Widget::drawChild (this=this@entry=0x67ca920, child=0x862c9b0, args=..., layer=layer@entry=0) at src/widget/Widget.cpp:311
#31 0x00007ffb31a54982 in rack::widget::Widget::draw (this=0x67ca920, args=...) at src/widget/Widget.cpp:280
#32 0x00007ffb31a58c06 in rack::window::Window::step (this=this@entry=0x6751720) at src/window/Window.cpp:499
#33 0x00007ffb31a58d48 in rack::window::Window::run (this=0x6751720) at src/window/Window.cpp:408
#34 0x00007ff63de01384 in main (argc=<optimized out>, argv=<optimized out>) at adapters/standalone.cpp:266
```

**Comment by alefnull** [comment]
thanks, yeah i expect there are a number of problems with the current state of things, as i'm still learning some new things for one of my new modules.

**Comment by SteveRussell33** [comment]
OK, no worries.

**Comment by alefnull** [comment]
the truth is i never actually expect people to be watching the repo and trying new changes lol

most of what i've been pushing the last few days has been so @dustinlacewell can take a look and help me out with some stuff.

**Comment by alefnull** [comment]
hey Steve,

i was wondering if you might give my most recent commit (8e4abbe) a try when you get a chance. i've made several changes and fixed several issues i myself was experiencing. i don't know if any of it will have solved your crash, but i'd be curious to find out, if you have the time at some point.

**Comment by SteveRussell33** [comment]
Rebuilt using latest commit, all good here, no crash from the browser or using the scope in the rack. Nice!

p.s. Loose screws get everywhere! ;)

**Comment by alefnull** [comment]
hey man, as the commit message and a very wise man once said, "screws fall out all the time. the world is an imperfect place."
